// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"createdAt"`
}

type Entry struct {
	ID        int64         `json:"id"`
	AccountID sql.NullInt64 `json:"accountId"`
	// can be negative positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Follow struct {
	FollowingUserID sql.NullInt32 `json:"followingUserId"`
	FollowedUserID  sql.NullInt32 `json:"followedUserId"`
	CreatedAt       sql.NullTime  `json:"createdAt"`
}

type Post struct {
	ID    int32          `json:"id"`
	Title sql.NullString `json:"title"`
	// Content of the post
	Body      sql.NullString `json:"body"`
	UserID    sql.NullInt32  `json:"userId"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"fromAccountId"`
	ToAccountID   int64     `json:"toAccountId"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"createdAt"`
}

type User struct {
	ID        int32          `json:"id"`
	Username  sql.NullString `json:"username"`
	Role      sql.NullString `json:"role"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}
